name = "nyxia-v3"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "NYXIA_MEMORY"
id = "d129baa51bc54f1e9ae8893369873fd2"

[[kv_namespaces]]
binding = "NYXIA_BOOKS"
id = "2d7ee25f73d64ad28054cb75b47315d1"

[[kv_namespaces]]
binding = "NYXIA_VAULT"
id = "c62f5d8ca37e450bb8c9efba5263214c"
